### ISSUE TITLE
unable to connect to phone with IP

### ISSUE THREAD

**Issue by LuxStatera** [mesquidar/adbsploit#1]
unable to connect to **.*.*.**:5555: Connection refused

**Comment by mesquidar** [comment]
Hi @LuxStatera , make sure the phone have the developer options enabled and usb debugging activated.
If continues refusing the connection: 
1. Connect via usb the phone on your computer and will appear on your phone a message select allow
2. Open ADBSploit and show the devices
3. **Select** the usb device
4. Execute **tcpip** and then specify your desired port
5. Execute **connect** then specify ip:port (192.168.X.X:XXXX)
6. Once the device is connected execute **devices** and will appear a new device
7. **Select** this new device and unplug the usb
8. Now you can use ADBSploit with your phone via WiFi

Hope it helps

Regards
Ruben
